# --------------------------------------------------
# the default filter shortcut is obscured by the fg plugin
# create another shortcut
[[mgr.prepend_keymap]]
on   = [ "f","t" ]
run  = "filter --smart"
desc = "filter"

[[mgr.prepend_keymap]]
on   = ['#', 'x']
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on   = ['#', 't']
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

# -------------------------------------------------- 
# bookmark manager
[[mgr.prepend_keymap]]
on = [ "b", "a" ]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "g" ]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = [ "b", "G" ]
run = "plugin yamb jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin yamb delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "b", "A" ]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "b", "r" ]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "b", "R" ]
run = "plugin yamb rename_by_fzf"
desc = "Rename bookmark by fzf"


# -------------------------------------------------- 
# project manager: save/restore tabs
#
[[mgr.prepend_keymap]]
on = [ "q" ]
run = "plugin projects quit"
desc = "Save last project and exit the process"

[[mgr.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = [ "P", "m" ]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = [ "P", "M" ]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"#

# -------------------------------------------------- 
#compress plugin

[[mgr.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"


# -------------------------------------------------- 
# what size plugin
[[mgr.prepend_keymap]]
on   = [ "c", "s" ]
run  = "plugin what-size --args='--clipboard'"
desc = "Calc size of selected or cwd" 

# -------------------------------------------------- 
# fg plugin - fd/ripgrep/fzf
[[mgr.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content (fuzzy match)"

[[mgr.prepend_keymap]]
on   = [ "f","G" ]
run  = "plugin fg --args='rg'"
desc = "find file by content (ripgrep match)"

[[mgr.prepend_keymap]]
on   = [ "f","f" ]
run  = "plugin fg --args='fzf'"
desc = "find file by filename"

[[mgr.prepend_keymap]]
on   = [ "f","a" ]
run  = "plugin fg --args='rga'"
desc = "find file by content (ripgrep-all)"
# -------------------------------------------------- 
# smart filter
# https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"
# -------------------------------------------------- 
# chmod plugin
[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
# -------------------------------------------------- 
# trash-cli plugin
[[mgr.prepend_keymap]]
on = ["c", "r"]
run = "plugin restore"
desc = "Restore last deleted files/folders"

# -------------------------------------------------- 
# file-extra-metadata
#https://github.com/boydaihungst/file-extra-metadata.yazi?tab=readme-ov-file
[[mgr.prepend_keymap]]
on = "<Tab>"
run = "spot"
desc = "Spot hovered file"
#
# -------------------------------------------------- 
# -------------------------------------------------- 
# -------------------------------------------------- 
# -------------------------------------------------- 
# -------------------------------------------------- 

