# https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
ratio = [0, 4, 4]
sort_by = "natural"
linemode = "size_and_mtime"
# git plugin
#
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[plugin]

prepend_previewers = [
    {name = "*.md", run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'}
]
append_previewers = [
  { name = "*", run = "file-extra-metadata" },
]

append_spotters = [
  { name = "*", run = "file-extra-metadata" },
]

[opener]

play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
]
edit = [
# when pressing O (capital O) this $EDITOR is an option
  # { run = '$EDITOR "$@"', block = false, for = "unix" },
  { run = '$EDITOR "$@"', orphan = true, block = false, for = "unix", desc = "Gvim" },

  # this is for bulk rename
  { run = 'vim "$@"', block = true, for = "unix", desc = "Vim" },

  { run = "%EDITOR% %*",  block = true, for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

extract = [
  { run = '~/data/scripts/linux/yazi-extract.sh "$1"', desc = "Extract to subfolder", for = "unix" },

  { run = 'ya pub extract --list %*', desc = "Extract here", for = "windows" }
]

[open]
prepend_rules = [
	# { name = "*.json", use = "edit" },

	# Multiple openers for a single rule
	# { name = "*.html", use = [ "open", "edit", "reveal" ] },
  # { name = "*.htm", use = [ "open", "edit" , "reveal"] },
  #
  { name = "*", use = [ "open", "edit", "reveal" ] }, 
]
append_rules = [
	# { name = "*", use = "edit" },
  # { name = "*", use = [ "open", "edit", "reveal" ] }, 
]

